### PR TITLE
Replace x86 dylib with universal dylib for macos

### PR DESCRIPTION
**Pull request by Piras314**
- To have M1 support

### CODE REVIEW

**Comment by Piras314** [comment]
@3ddelano

**Comment by 3ddelano** [comment]
Hey thanks for this pull request, but it really should be a part of the original repo which is used here. This is the repo [Unix socket](https://github.com/Abdera7mane/Godot-UnixSocket)

**Comment by 3ddelano** [comment]
I don't have any way to test this so I'll merge it for now but if the original repo updates the libs will be reverted to x86.

**Comment by Piras314** [comment]
Alright, perfect! This doesn't belong in that repo since the only inclusion of the x86 dylib is in the release and I'm not sure how I can PR into release... Let me know if you have any issues though!

**Comment by 3ddelano** [comment]
Well the release is from the GitHub workflow, so you can try editing the workflow yaml file to include the command for universal builds.

**Comment by Abdera7mane** [comment]
Hi @CMDR-Piboy314, I would appreciate to know the steps you took to compile the GDNative Library. I believe this is a nice thing to have on [Godot Unix Socket](https://github.com/Abdera7mane/Godot-UnixSocket), I could not test it myself and it is a bit hard to try out things without a proper M1 chip device. I apology for reviving this PR.

**Comment by Piras314** [comment]
@Abdera7mane No worries, however I no longer have that mac and I don't remember what commands I ran to compile GDNative. It did work though so as long as you don't need a version newer than that one from may you can keep it (when / if that time comes we'll have to wait for another mac to come along)

**Comment by Abdera7mane** [comment]
All right then, thanks for replying.

**Pull request merged**
